name: GitHub Action Slack Notify CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
        env:
          CI: true

      - name: yarn install and test
        run: |
          yarn
          yarn test
        env:
          CI: true

      - name: yarn build
        run: yarn build
      # - name: release
      #   if: ${{ endsWith(github.ref, '/main') }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release
